### ISSUE TITLE
[Bug]: Percent calculation timeout error

### ISSUE THREAD

**Issue by tpeacock19** [maximbaz/wluma#65] opened 2022-12-13 13:43 UTC
### Steps for reproducing the issue

Start wluma on my machine with the following config:

```toml
[als.webcam]
video = 4
thresholds = { 0 = "night", 15 = "dark", 30 = "dim", 45 = "normal", 60 = "bright", 75 = "outdoors" }

[[output.backlight]]
name = "eDP-1"
path = "/sys/class/backlight/amdgpu_bl0"
capturer = "wlroots"

```

### What is the buggy behavior?

wluma does not run after identifying the correct output.

### What is the expected behavior?

wluma should run without error.

### Logs

<details open>
<summary>wluma.log</summary>

```shell
src/archlinux/wluma
 ❯ RUST_LOG=trace RUST_BACKTRACE=full vk_radv cargo run                 main 306d ⬡
    Finished dev [unoptimized + debuginfo] target(s) in 0.10s
     Running `target/debug/wluma`
[2022-12-11T03:19:51Z DEBUG wluma] Using Config {
        als: Webcam {
            video: 4,
            thresholds: {
                75: "outdoors",
                0: "night",
                60: "bright",
                30: "dim",
                45: "normal",
                15: "dark",
            },
        },
        output: [
            Backlight(
                BacklightOutput {
                    name: "eDP-1",
                    path: "/sys/class/backlight/amdgpu_bl0",
                    capturer: Wlroots,
                    min_brightness: 1,
                },
            ),
        ],
    }
[2022-12-11T03:19:51Z INFO  wluma] Continue adjusting brightness and wluma will learn your preference over time.
[2022-12-11T03:19:51Z TRACE wluma::als::webcam] ALS (webcam): outdoors (100)
[2022-12-11T03:19:51Z DEBUG wluma::frame::capturer::wlroots] Using output 'IVO 0x057D (eDP-1)' for config 'eDP-1'
[2022-12-11T03:19:51Z TRACE wluma::als::webcam] ALS (webcam): outdoors (100)
[2022-12-11T03:19:51Z TRACE wluma::als::webcam] ALS (webcam): outdoors (100)
[2022-12-11T03:19:51Z TRACE wluma::als::webcam] ALS (webcam): outdoors (100)
[2022-12-11T03:19:52Z TRACE wluma::als::webcam] ALS (webcam): outdoors (100)
[2022-12-11T03:19:52Z TRACE wluma::als::webcam] ALS (webcam): outdoors (100)
[2022-12-11T03:19:52Z TRACE wluma::als::webcam] ALS (webcam): night (7)
[2022-12-11T03:19:52Z TRACE wluma::als::webcam] ALS (webcam): night (7)
[2022-12-11T03:19:52Z TRACE wluma::als::webcam] ALS (webcam): night (7)
[2022-12-11T03:19:52Z TRACE wluma::als::webcam] ALS (webcam): night (7)
[2022-12-11T03:19:52Z TRACE wluma::als::webcam] ALS (webcam): night (7)
thread 'predictor-eDP-1' panicked at 'Unable to compute luma percent: TIMEOUT', src/frame/capturer/wlroots.rs:128:26
stack backtrace:
   0:     0x55e2c939e1ad - std::backtrace_rs::backtrace::libunwind::trace::h8217d0a8f3fd2f41
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55e2c939e1ad - std::backtrace_rs::backtrace::trace_unsynchronized::h308103876b3af410
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55e2c939e1ad - std::sys_common::backtrace::_print_fmt::hc208018c6153605e
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x55e2c939e1ad - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf89a7ed694dfb585
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x55e2c93c11dc - core::fmt::write::h21038c1382fe4264
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/fmt/mod.rs:1197:17
   5:     0x55e2c939b441 - std::io::Write::write_fmt::h7dbb1c9a3c254aef
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/io/mod.rs:1672:15
   6:     0x55e2c939fb85 - std::sys_common::backtrace::_print::h4e8889719c9ddeb8
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x55e2c939fb85 - std::sys_common::backtrace::print::h1506fe2cb3022667
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x55e2c939fb85 - std::panicking::default_hook::{{closure}}::hd9d7ce2a8a782440
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:295:22
   9:     0x55e2c939f8a6 - std::panicking::default_hook::h5b16ec25444b1b5d
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:314:9
  10:     0x55e2c8e577a3 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h18f9b59372de987a
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/alloc/src/boxed.rs:1965:9
  11:     0x55e2c8efda6b - wluma::main::{{closure}}::h8f2587462ebf5029
                               at /home/user/src/archlinux/wluma/src/main.rs:14:9
  12:     0x55e2c93a022a - std::panicking::rust_panic_with_hook::hb0138cb6e6fea3e4
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:702:17
  13:     0x55e2c93a0067 - std::panicking::begin_panic_handler::{{closure}}::h4cb67095557cd1aa
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:588:13
  14:     0x55e2c939e664 - std::sys_common::backtrace::__rust_end_short_backtrace::h2bfcac279dcdc911
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:138:18
  15:     0x55e2c939fd99 - rust_begin_unwind
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:584:5
  16:     0x55e2c93bf223 - core::panicking::panic_fmt::h1de71520faaa17d3
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:142:14
  17:     0x55e2c93bf4d3 - core::result::unwrap_failed::hc0baa33ef8bc7db8
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/result.rs:1805:5
  18:     0x55e2c8f05bf8 - core::result::Result<T,E>::expect::ha29aa314488aa8bd
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/result.rs:1055:23
  19:     0x55e2c8e6bcb4 - wluma::frame::capturer::wlroots::Capturer::capture_frame::{{closure}}::ha72c3da1b6b9ecc6
                               at /home/user/src/archlinux/wluma/src/frame/capturer/wlroots.rs:125:32
  20:     0x55e2c8ef828a - wayland_client::proxy::Main<I>::quick_assign::{{closure}}::h91bc8b8c43151e02
                               at /home/user/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/wayland-client-0.29.4/src/proxy.rs:273:64
  21:     0x55e2c8eef49c - wayland_commons::filter::Filter<E>::send::h2f4523b57e127e1a
                               at /home/user/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/wayland-commons-0.29.4/src/filter.rs:100:13
  22:     0x55e2c8e8b2aa - wayland_client::imp::proxy::ProxyInner::assign::{{closure}}::h9c02564c5b59b747
                               at /home/user/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/wayland-client-0.29.4/src/native_lib/proxy.rs:257:57
  23:     0x55e2c9170db3 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h5e3bb732b04d1149
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/alloc/src/boxed.rs:1965:9
  24:     0x55e2c916d230 - wayland_client::imp::proxy::proxy_dispatcher::{{closure}}::{{closure}}::hf0b9b66a75586466
                               at /home/user/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/wayland-client-0.29.4/src/native_lib/proxy.rs:418:25
  25:     0x55e2c9174997 - scoped_tls::ScopedKey<T>::with::h3777d35c56da1e14
                               at /home/user/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-1.0.0/src/lib.rs:171:13
  26:     0x55e2c916bb91 - wayland_client::imp::proxy::proxy_dispatcher::{{closure}}::hb3c2a045a7411ea3
                               at /home/user/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/wayland-client-0.29.4/src/native_lib/proxy.rs:415:21
  27:     0x55e2c91728af - std::panicking::try::do_call::h4791231fab94fe69
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:492:40
  28:     0x55e2c91735eb - __rust_try
  29:     0x55e2c9172734 - std::panicking::try::ha69f8a1463c4ddda
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:456:19
  30:     0x55e2c916f861 - std::panic::catch_unwind::h62efa39d5b2ece0d
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panic.rs:137:14
  31:     0x55e2c916b355 - wayland_client::imp::proxy::proxy_dispatcher::h936486be88d714ff
                               at /home/user/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/wayland-client-0.29.4/src/native_lib/proxy.rs:387:15
  32:     0x7f4501ad7d65 - <unknown>
  33:     0x7f4501ad7ffc - wl_display_dispatch_queue_pending
  34:     0x55e2c8e1802f - wayland_client::imp::event_queue::EventQueueInner::dispatch::{{closure}}::he5be4c6b209acefd
                               at /home/user/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/wayland-client-0.29.4/src/native_lib/event_queue.rs:43:17
  35:     0x55e2c8e77a3a - scoped_tls::ScopedKey<T>::set::h268c1a44093cf2c2
                               at /home/user/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-1.0.0/src/lib.rs:137:9
  36:     0x55e2c8e18357 - wayland_client::imp::event_queue::with_dispatch_meta::hb1ca4c5c9ed07d47
                               at /home/user/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/wayland-client-0.29.4/src/native_lib/event_queue.rs:24:5
  37:     0x55e2c8e17f89 - wayland_client::imp::event_queue::EventQueueInner::dispatch::hbf22d8c60d2fbcde
                               at /home/user/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/wayland-client-0.29.4/src/native_lib/event_queue.rs:41:9
  38:     0x55e2c8f2de9d - wayland_client::event_queue::EventQueue::dispatch::h258dff99bbbecfff
                               at /home/user/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/wayland-client-0.29.4/src/event_queue.rs:152:9
  39:     0x55e2c8e36bb5 - <wluma::frame::capturer::wlroots::Capturer as wluma::frame::capturer::Capturer>::run::h7e624e302a4ca6c5
                               at /home/user/src/archlinux/wluma/src/frame/capturer/wlroots.rs:60:13
  40:     0x55e2c8eff146 - wluma::main::{{closure}}::{{closure}}::hc1116d90a2b1acb9
                               at /home/user/src/archlinux/wluma/src/main.rs:87:29
  41:     0x55e2c8f0f24c - std::sys_common::backtrace::__rust_begin_short_backtrace::ha867c14475f61191
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:122:18
  42:     0x55e2c8e1fcb0 - std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}::h48905f39b26bcdf2
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/thread/mod.rs:505:17
  43:     0x55e2c8ef7810 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h894b536c22485698
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panic/unwind_safe.rs:271:9
  44:     0x55e2c8f1502a - std::panicking::try::do_call::h2d01533784ba40f1
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:492:40
  45:     0x55e2c8f1579b - __rust_try
  46:     0x55e2c8f14da1 - std::panicking::try::hd88ba560baf39e41
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:456:19
[2022-12-11T03:19:52Z TRACE wluma::als::webcam] ALS (webcam): night (7)
  47:     0x55e2c8e659f0 - std::panic::catch_unwind::h26efa7a672967e7e
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panic.rs:137:14
  48:     0x55e2c8e1ef0b - std::thread::Builder::spawn_unchecked_::{{closure}}::h014fcc1dd2f9e66b
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/thread/mod.rs:504:30
  49:     0x55e2c8e7a0be - core::ops::function::FnOnce::call_once{{vtable.shim}}::h0bb2c2c1c85ec0a2
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/ops/function.rs:248:5
  50:     0x55e2c93a2f43 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h1680342795a2dc08
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/alloc/src/boxed.rs:1951:9
  51:     0x55e2c93a2f43 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h45204a69827b0e83
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/alloc/src/boxed.rs:1951:9
  52:     0x55e2c93a2f43 - std::sys::unix::thread::Thread::new::thread_start::h5d4e11bbda4161c8
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys/unix/thread.rs:108:17
  53:     0x7f450177c8fd - <unknown>
  54:     0x7f45017fea60 - <unknown>
  55:                0x0 - <unknown>

```

</details>

<details open>
<summary>syslog</summary>

```sh
Dec 10 20:19:51 kernel: [30707.226531] gmc_v9_0_process_interrupt: 152 callbacks suppressed
Dec 10 20:19:51 kernel: [30707.226538] amdgpu 0000:06:00.0: amdgpu: [gfxhub0] no-retry page fault (src_id:0 ring:24 vmid:6 pasid:32778, for process wluma pid 731265 thread predictor-eDP-1 pid 731268)
Dec 10 20:19:51 kernel: [30707.226547] amdgpu 0000:06:00.0: amdgpu:   in page starting at address 0x0000800100e08000 from IH client 0x1b (UTCL2)
Dec 10 20:19:51 kernel: [30707.226553] amdgpu 0000:06:00.0: amdgpu: VM_L2_PROTECTION_FAULT_STATUS:0x00601031
Dec 10 20:19:51 kernel: [30707.226555] amdgpu 0000:06:00.0: amdgpu:     Faulty UTCL2 client ID: TCP (0x8)
Dec 10 20:19:51 kernel: [30707.226558] amdgpu 0000:06:00.0: amdgpu:     MORE_FAULTS: 0x1
Dec 10 20:19:51 kernel: [30707.226559] amdgpu 0000:06:00.0: amdgpu:     WALKER_ERROR: 0x0
Dec 10 20:19:51 kernel: [30707.226561] amdgpu 0000:06:00.0: amdgpu:     PERMISSION_FAULTS: 0x3
Dec 10 20:19:51 kernel: [30707.226563] amdgpu 0000:06:00.0: amdgpu:     MAPPING_ERROR: 0x0
Dec 10 20:19:51 kernel: [30707.226564] amdgpu 0000:06:00.0: amdgpu:     RW: 0x0
Dec 10 20:19:51 kernel: [30707.226567] amdgpu 0000:06:00.0: amdgpu: [gfxhub0] no-retry page fault (src_id:0 ring:24 vmid:6 pasid:32778, for process wluma pid 731265 thread predictor-eDP-1 pid 731268)
Dec 10 20:19:51 kernel: [30707.226572] amdgpu 0000:06:00.0: amdgpu:   in page starting at address 0x0000800100e09000 from IH client 0x1b (UTCL2)
Dec 10 20:19:51 kernel: [30707.226576] amdgpu 0000:06:00.0: amdgpu: VM_L2_PROTECTION_FAULT_STATUS:0x00000000
Dec 10 20:19:51 kernel: [30707.226578] amdgpu 0000:06:00.0: amdgpu:     Faulty UTCL2 client ID: CB (0x0)
Dec 10 20:19:51 kernel: [30707.226580] amdgpu 0000:06:00.0: amdgpu:     MORE_FAULTS: 0x0
Dec 10 20:19:51 kernel: [30707.226581] amdgpu 0000:06:00.0: amdgpu:     WALKER_ERROR: 0x0
Dec 10 20:19:51 kernel: [30707.226583] amdgpu 0000:06:00.0: amdgpu:     PERMISSION_FAULTS: 0x0
Dec 10 20:19:51 kernel: [30707.226584] amdgpu 0000:06:00.0: amdgpu:     MAPPING_ERROR: 0x0
Dec 10 20:19:51 kernel: [30707.226586] amdgpu 0000:06:00.0: amdgpu:     RW: 0x0
Dec 10 20:19:51 kernel: [30707.226588] amdgpu 0000:06:00.0: amdgpu: [gfxhub0] no-retry page fault (src_id:0 ring:24 vmid:6 pasid:32778, for process wluma pid 731265 thread predictor-eDP-1 pid 731268)
Dec 10 20:19:51 kernel: [30707.226592] amdgpu 0000:06:00.0: amdgpu:   in page starting at address 0x0000800100e0a000 from IH client 0x1b (UTCL2)
Dec 10 20:19:51 kernel: [30707.226595] amdgpu 0000:06:00.0: amdgpu: VM_L2_PROTECTION_FAULT_STATUS:0x00000000
Dec 10 20:19:51 kernel: [30707.226597] amdgpu 0000:06:00.0: amdgpu:     Faulty UTCL2 client ID: CB (0x0)
Dec 10 20:19:51 kernel: [30707.226599] amdgpu 0000:06:00.0: amdgpu:     MORE_FAULTS: 0x0
Dec 10 20:19:51 kernel: [30707.226600] amdgpu 0000:06:00.0: amdgpu:     WALKER_ERROR: 0x0
Dec 10 20:19:51 kernel: [30707.226602] amdgpu 0000:06:00.0: amdgpu:     PERMISSION_FAULTS: 0x0
Dec 10 20:19:51 kernel: [30707.226603] amdgpu 0000:06:00.0: amdgpu:     MAPPING_ERROR: 0x0
Dec 10 20:19:51 kernel: [30707.226605] amdgpu 0000:06:00.0: amdgpu:     RW: 0x0
Dec 10 20:19:51 kernel: [30707.226607] amdgpu 0000:06:00.0: amdgpu: [gfxhub0] no-retry page fault (src_id:0 ring:24 vmid:6 pasid:32778, for process wluma pid 731265 thread predictor-eDP-1 pid 731268)
Dec 10 20:19:51 kernel: [30707.226610] amdgpu 0000:06:00.0: amdgpu:   in page starting at address 0x0000800100e0b000 from IH client 0x1b (UTCL2)
Dec 10 20:19:51 kernel: [30707.226614] amdgpu 0000:06:00.0: amdgpu: VM_L2_PROTECTION_FAULT_STATUS:0x00000000
Dec 10 20:19:51 kernel: [30707.226616] amdgpu 0000:06:00.0: amdgpu:     Faulty UTCL2 client ID: CB (0x0)
Dec 10 20:19:51 kernel: [30707.226617] amdgpu 0000:06:00.0: amdgpu:     MORE_FAULTS: 0x0
Dec 10 20:19:51 kernel: [30707.226619] amdgpu 0000:06:00.0: amdgpu:     WALKER_ERROR: 0x0
Dec 10 20:19:51 kernel: [30707.226620] amdgpu 0000:06:00.0: amdgpu:     PERMISSION_FAULTS: 0x0
Dec 10 20:19:51 kernel: [30707.226622] amdgpu 0000:06:00.0: amdgpu:     MAPPING_ERROR: 0x0
Dec 10 20:19:51 kernel: [30707.226624] amdgpu 0000:06:00.0: amdgpu:     RW: 0x0
Dec 10 20:19:51 kernel: [30707.226625] amdgpu 0000:06:00.0: amdgpu: [gfxhub0] no-retry page fault (src_id:0 ring:24 vmid:6 pasid:32778, for process wluma pid 731265 thread predictor-eDP-1 pid 731268)
Dec 10 20:19:51 kernel: [30707.226629] amdgpu 0000:06:00.0: amdgpu:   in page starting at address 0x0000800100e01000 from IH client 0x1b (UTCL2)
Dec 10 20:19:51 kernel: [30707.226632] amdgpu 0000:06:00.0: amdgpu: VM_L2_PROTECTION_FAULT_STATUS:0x00000000
Dec 10 20:19:51 kernel: [30707.226634] amdgpu 0000:06:00.0: amdgpu:     Faulty UTCL2 client ID: CB (0x0)
Dec 10 20:19:51 kernel: [30707.226636] amdgpu 0000:06:00.0: amdgpu:     MORE_FAULTS: 0x0
Dec 10 20:19:51 kernel: [30707.226637] amdgpu 0000:06:00.0: amdgpu:     WALKER_ERROR: 0x0
Dec 10 20:19:51 kernel: [30707.226639] amdgpu 0000:06:00.0: amdgpu:     PERMISSION_FAULTS: 0x0
Dec 10 20:19:51 kernel: [30707.226640] amdgpu 0000:06:00.0: amdgpu:     MAPPING_ERROR: 0x0
Dec 10 20:19:51 kernel: [30707.226642] amdgpu 0000:06:00.0: amdgpu:     RW: 0x0
Dec 10 20:19:51 kernel: [30707.226644] amdgpu 0000:06:00.0: amdgpu: [gfxhub0] no-retry page fault (src_id:0 ring:24 vmid:6 pasid:32778, for process wluma pid 731265 thread predictor-eDP-1 pid 731268)
Dec 10 20:19:51 kernel: [30707.226647] amdgpu 0000:06:00.0: amdgpu:   in page starting at address 0x0000800100e00000 from IH client 0x1b (UTCL2)
Dec 10 20:19:51 kernel: [30707.226651] amdgpu 0000:06:00.0: amdgpu: VM_L2_PROTECTION_FAULT_STATUS:0x00000000
Dec 10 20:19:51 kernel: [30707.226653] amdgpu 0000:06:00.0: amdgpu:     Faulty UTCL2 client ID: CB (0x0)
Dec 10 20:19:51 kernel: [30707.226654] amdgpu 0000:06:00.0: amdgpu:     MORE_FAULTS: 0x0
Dec 10 20:19:51 kernel: [30707.226656] amdgpu 0000:06:00.0: amdgpu:     WALKER_ERROR: 0x0
Dec 10 20:19:51 kernel: [30707.226658] amdgpu 0000:06:00.0: amdgpu:     PERMISSION_FAULTS: 0x0
Dec 10 20:19:51 kernel: [30707.226659] amdgpu 0000:06:00.0: amdgpu:     MAPPING_ERROR: 0x0
Dec 10 20:19:51 kernel: [30707.226661] amdgpu 0000:06:00.0: amdgpu:     RW: 0x0
Dec 10 20:19:51 kernel: [30707.226663] amdgpu 0000:06:00.0: amdgpu: [gfxhub0] no-retry page fault (src_id:0 ring:24 vmid:6 pasid:32778, for process wluma pid 731265 thread predictor-eDP-1 pid 731268)
Dec 10 20:19:51 kernel: [30707.226666] amdgpu 0000:06:00.0: amdgpu:   in page starting at address 0x0000800100e02000 from IH client 0x1b (UTCL2)
Dec 10 20:19:51 kernel: [30707.226670] amdgpu 0000:06:00.0: amdgpu: VM_L2_PROTECTION_FAULT_STATUS:0x00000000
Dec 10 20:19:51 kernel: [30707.226671] amdgpu 0000:06:00.0: amdgpu:     Faulty UTCL2 client ID: CB (0x0)
Dec 10 20:19:51 kernel: [30707.226673] amdgpu 0000:06:00.0: amdgpu:     MORE_FAULTS: 0x0
Dec 10 20:19:51 kernel: [30707.226675] amdgpu 0000:06:00.0: amdgpu:     WALKER_ERROR: 0x0
Dec 10 20:19:51 kernel: [30707.226676] amdgpu 0000:06:00.0: amdgpu:     PERMISSION_FAULTS: 0x0
Dec 10 20:19:51 kernel: [30707.226678] amdgpu 0000:06:00.0: amdgpu:     MAPPING_ERROR: 0x0
Dec 10 20:19:51 kernel: [30707.226679] amdgpu 0000:06:00.0: amdgpu:     RW: 0x0
Dec 10 20:19:51 kernel: [30707.226681] amdgpu 0000:06:00.0: amdgpu: [gfxhub0] no-retry page fault (src_id:0 ring:24 vmid:6 pasid:32778, for process wluma pid 731265 thread predictor-eDP-1 pid 731268)
Dec 10 20:19:51 kernel: [30707.226685] amdgpu 0000:06:00.0: amdgpu:   in page starting at address 0x0000800100e08000 from IH client 0x1b (UTCL2)
Dec 10 20:19:51 kernel: [30707.226688] amdgpu 0000:06:00.0: amdgpu: VM_L2_PROTECTION_FAULT_STATUS:0x00000000
Dec 10 20:19:51 kernel: [30707.226690] amdgpu 0000:06:00.0: amdgpu:     Faulty UTCL2 client ID: CB (0x0)
Dec 10 20:19:51 kernel: [30707.226692] amdgpu 0000:06:00.0: amdgpu:     MORE_FAULTS: 0x0
Dec 10 20:19:51 kernel: [30707.226693] amdgpu 0000:06:00.0: amdgpu:     WALKER_ERROR: 0x0
Dec 10 20:19:51 kernel: [30707.226695] amdgpu 0000:06:00.0: amdgpu:     PERMISSION_FAULTS: 0x0
Dec 10 20:19:51 kernel: [30707.226696] amdgpu 0000:06:00.0: amdgpu:     MAPPING_ERROR: 0x0
Dec 10 20:19:51 kernel: [30707.226698] amdgpu 0000:06:00.0: amdgpu:     RW: 0x0
Dec 10 20:19:51 kernel: [30707.226700] amdgpu 0000:06:00.0: amdgpu: [gfxhub0] no-retry page fault (src_id:0 ring:24 vmid:6 pasid:32778, for process wluma pid 731265 thread predictor-eDP-1 pid 731268)
Dec 10 20:19:51 kernel: [30707.226703] amdgpu 0000:06:00.0: amdgpu:   in page starting at address 0x0000800100de9000 from IH client 0x1b (UTCL2)
Dec 10 20:19:51 kernel: [30707.226707] amdgpu 0000:06:00.0: amdgpu: VM_L2_PROTECTION_FAULT_STATUS:0x00000000
Dec 10 20:19:51 kernel: [30707.226708] amdgpu 0000:06:00.0: amdgpu:     Faulty UTCL2 client ID: CB (0x0)
Dec 10 20:19:51 kernel: [30707.226710] amdgpu 0000:06:00.0: amdgpu:     MORE_FAULTS: 0x0
Dec 10 20:19:51 kernel: [30707.226712] amdgpu 0000:06:00.0: amdgpu:     WALKER_ERROR: 0x0
Dec 10 20:19:51 kernel: [30707.226713] amdgpu 0000:06:00.0: amdgpu:     PERMISSION_FAULTS: 0x0
Dec 10 20:19:51 kernel: [30707.226715] amdgpu 0000:06:00.0: amdgpu:     MAPPING_ERROR: 0x0
Dec 10 20:19:51 kernel: [30707.226716] amdgpu 0000:06:00.0: amdgpu:     RW: 0x0
Dec 10 20:19:51 kernel: [30707.226718] amdgpu 0000:06:00.0: amdgpu: [gfxhub0] no-retry page fault (src_id:0 ring:24 vmid:6 pasid:32778, for process wluma pid 731265 thread predictor-eDP-1 pid 731268)
Dec 10 20:19:51 kernel: [30707.226722] amdgpu 0000:06:00.0: amdgpu:   in page starting at address 0x0000800100e0b000 from IH client 0x1b (UTCL2)
Dec 10 20:19:51 kernel: [30707.226725] amdgpu 0000:06:00.0: amdgpu: VM_L2_PROTECTION_FAULT_STATUS:0x00000000
Dec 10 20:19:51 kernel: [30707.226727] amdgpu 0000:06:00.0: amdgpu:     Faulty UTCL2 client ID: CB (0x0)
Dec 10 20:19:51 kernel: [30707.226729] amdgpu 0000:06:00.0: amdgpu:     MORE_FAULTS: 0x0
Dec 10 20:19:51 kernel: [30707.226730] amdgpu 0000:06:00.0: amdgpu:     WALKER_ERROR: 0x0
Dec 10 20:19:51 kernel: [30707.226732] amdgpu 0000:06:00.0: amdgpu:     PERMISSION_FAULTS: 0x0
Dec 10 20:19:51 kernel: [30707.226734] amdgpu 0000:06:00.0: amdgpu:     MAPPING_ERROR: 0x0
Dec 10 20:19:51 kernel: [30707.226736] amdgpu 0000:06:00.0: amdgpu:     RW: 0x0
Dec 10 20:20:02 kernel: [30717.636063] [drm:amdgpu_job_timedout [amdgpu]] *ERROR* ring gfx timeout, but soft recovered

```

</details>

### Version

I am running this commit version 0c49755fdcf19b22841844df6508f29c31975ce2. I have built it from source.

### Environment

```shell
LSB Version:	n/a
Distributor ID:	Arch
Description:	Arch Linux
Release:	rolling
Codename:	n/a
Linux baalsecundus 6.0.12-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Thu, 08 Dec 2022 11:03:40 +0000 x86_64 GNU/Linux
amd-vulkan-prefixes 1-1
clang 14.0.6-4
clang13 13.0.1-4
lib32-clang 14.0.6-2
lib32-vulkan-amdgpu-pro 22.20.4_1498766-2
lib32-vulkan-icd-loader 1.3.235-1
lib32-vulkan-mesa-layers 22.2.3-1
lib32-vulkan-radeon 22.2.3-1
rust-analyzer 20221205-1
rustup 1.25.1-2
swayidle-git 1.8.0.r8.g4b9e70c-1
vulkan-amdgpu-pro 22.20.5_1511376-2
vulkan-headers 1:1.3.235-1
vulkan-icd-loader 1.3.235-1
vulkan-mesa-layers 22.2.3-1
vulkan-radeon 22.2.3-1
vulkan-swrast 22.2.3-1
vulkan-tools 1.3.226-1
vulkan-validation-layers 1.3.231.1-1
wlroots 0.15.1-6
river-0.2.0-dev.138+e603c54
```

**Comment by maximbaz** [comment] 2022-12-13 18:33
Could you please confirm if you have one or two GPUs, and in the latter case, which one do you use? The `VM_L2_PROTECTION_FAULT_STATUS` issue seems to be quite frequent if I google for it (e.g. [1](https://bbs.archlinux.org/viewtopic.php?id=266358&p=5), [2](https://gitlab.freedesktop.org/drm/amd/-/issues/1609#note_1369839)), so I wonder if it's either a driver problem, or on the other hand a wluma's problem of using discrete GPU (we have [at least one](https://github.com/maximbaz/wluma/issues/63) other issue for this case, btw, not necessarily a duplicate, but could be relevant), or something else entirely.

**Comment by tpeacock19** [comment] 2022-12-13 23:43
Oh sorry, I just have the amd T14 Gen 1 laptop with AMD Ryzen 7 Pro 4750U. I believe it is just Radeon integrated graphics. I came across those same issues so it may not be a wluma thing. It's the only program I experience this with, but I don't play a lot of games.

**Comment by maximbaz** [comment] 2024-10-21 17:29
Hey, I know this is super old issue but since then I learned a bit more about how to debug Vulkan issues, would you be interested in debugging this further, or this is no longer relevant for you?

**Comment by maximbaz** [comment] 2024-12-25 21:31
Closing as not actionable, please do comment here or in a new issue if someone is able to reproduce and willing to help debugging :pray:

**Closed by maximbaz** 2024-12-25 21:31 UTC
