### ISSUE TITLE
[Bug]: not version

### ISSUE THREAD

**Issue by newyorkthink** [maximbaz/wluma#76] opened 2023-07-07 10:35 UTC
### Steps for reproducing the issue

![image](https://github.com/maximbaz/wluma/assets/87791643/92217db1-e195-4e97-abf8-ef5554383bf5)

### What is the buggy behavior?

1

### What is the expected behavior?

1

### Logs

```shell
RUST_LOG=debug wluma
```

### Version

1

### Environment

```shell
lsb_release -a; uname -a; pgrep -l sway; pacman -Q | egrep "(wlroots|vulkan|sway|clang|rust)"; dpkg -l | egrep "(wlroots|vulkan|sway|clang|rust)"
```

**Comment by maximbaz** [comment] 2023-07-07 16:25
I have no idea what you wanted to express.

**Comment by newyorkthink** [comment] 2023-07-08 00:24
> I have no idea what you wanted to express.我不知道你想表达什么。

is not new package, is three line, but new version package, is not show

**Comment by maximbaz** [comment] 2023-07-08 09:36
Unfortunately it's hard to understand still, can you please try to explain in as much details as you can, what is wrong and what you expected, using specific examples if possible?

**Comment by cyrinux** [comment] 2023-07-08 11:37
@maximbaz @newyorkthink I understand the issue, the binaries files are missing in the release compared to the previous releases.

**Comment by maximbaz** [comment] 2024-10-21 21:01
Closing as duplicate of https://github.com/maximbaz/wluma/issues/97, will eventually solve :crossed_fingers:

**Closed by maximbaz** 2024-10-21 21:01 UTC
