### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by cog25** [maximbaz/wluma#50] opened 2022-05-28 16:38 UTC
### Steps for reproducing the issue

just run `wluma` or enable `wluma` service

### What is the buggy behavior?

```
thread 'predictor-eDP-1' panicked at 'assertion failed: `(left == right)`
```

### What is the expected behavior?

wluma changes my laptop's backlight

### Logs

```shell
$ RUST_LOG=debug wluma
[2022-05-28T16:34:36Z DEBUG wluma] Using Config {
        als: Webcam {
            video: 1,
            thresholds: {
                0: "night",
                30: "dim",
                60: "bright",
                75: "outdoors",
                45: "normal",
                15: "dark",
            },
        },
        output: [
            Backlight(
                BacklightOutput {
                    name: "eDP-1",
                    path: "/sys/class/backlight/intel_backlight",
                    capturer: Wlroots,
                    min_brightness: 1,
                },
            ),
        ],
    }
[2022-05-28T16:34:36Z INFO  wluma] Continue adjusting brightness and wluma will learn your preference over time.
[2022-05-28T16:34:36Z DEBUG wluma::frame::capturer::wlroots] Using output 'Unknown 0x07BE 0x00000000 (eDP-1)' for config 'eDP-1'
thread 'predictor-eDP-1' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `2`: Frames with multiple objects are not supported yet', src/frame/vulkan.rs:145:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Version

```
$ sudo pacman -Qi wluma
Name            : wluma-git
Version         : 4.1.2.r1.g0c49755-1
Description     : Automatic brightness adjustment based on screen contents and ALS
Architecture    : x86_64
URL             : https://github.com/maximbaz/wluma
Licenses        : ISC
Groups          : None
Provides        : wluma
Depends On      : vulkan-icd-loader  systemd-libs  glibc  gcc-libs  v4l-utils
Optional Deps   : vulkan-driver: for using capturer=wlroots in config.toml [installed]
                  wayland: for using capturer=wlroots in config.toml [installed]
Required By     : None
Optional For    : None
Conflicts With  : wluma
Replaces        : None
Installed Size  : 2.46 MiB
Packager        : Unknown Packager
Build Date      : Sun 29 May 2022 01:10:17 AM KST
Install Date    : Sun 29 May 2022 01:13:48 AM KST
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : None
```

### Environment

```shell
$ lsb_release -a; uname -a; pgrep -l sway; pacman -Q | egrep "(wlroots|vulkan|sway|clang|rust)"; dpkg -l | egrep "(wlroots|vulkan|sway|clang|rust)"
LSB Version:	n/a
Distributor ID:	Arch
Description:	Arch Linux
Release:	rolling
Codename:	n/a
Linux zenbookarch 5.17.9-zen1-1-zen #1 ZEN SMP PREEMPT Wed, 18 May 2022 17:58:27 +0000 x86_64 GNU/Linux
5637 sway
5681 swaybg
clang 13.0.1-2
intel-opencl-clang 13.0.0.r6+gd06733f-1
lib32-vulkan-icd-loader 1.3.213-1
lib32-vulkan-intel 22.1.0-1
rustup 1.24.3-2
sway 1:1.7-9
swaybg-git r120.de77798-1
vulkan-headers 1:1.3.213-1
vulkan-icd-loader 1.3.213-1
vulkan-intel 22.1.0-1
vulkan-validation-layers 1.3.211.0-1
wlroots 0.15.1-5
wlroots-git-debug 0.16.0.r5530.75d31509-1
zsh: command not found: dpkg
```

**Comment by maximbaz** [comment] 2022-05-28 22:44
Thank you for the detailed report, it's a duplicate of #8 and unfortunately I don't know when I'll be able to get this to properly be implemented - but there exists a workaround, which I myself use on my own laptop to avoid this exact issue, please see that thread 👍

**Closed by maximbaz** 2022-05-28 22:44 UTC
